2024-02-28 15:47:07,539 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-28 15:47:07,539 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Configure stats pid to 8170
2024-02-28 15:47:07,539 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Loading settings from /home/sadbhawna/.config/wandb/settings
2024-02-28 15:47:07,539 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Loading settings from /home/sadbhawna/Desktop/cs6910_assignment1/wandb/settings
2024-02-28 15:47:07,539 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'cs23d014_assignment_1', 'entity': 'cs23d014', 'root_dir': '/home/sadbhawna/Desktop/cs6910_assignment1', 'run_id': '09md131f', 'sweep_param_path': '/home/sadbhawna/Desktop/cs6910_assignment1/wandb/sweep-d3nuqt8j/config-09md131f.yaml', 'sweep_id': 'd3nuqt8j'}
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'sweep_functionality.py', 'program_abspath': '/home/sadbhawna/Desktop/cs6910_assignment1/sweep_functionality.py', 'program': '/home/sadbhawna/Desktop/cs6910_assignment1/sweep_functionality.py'}
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_init.py:_log_setup():526] Logging user logs to /home/sadbhawna/Desktop/cs6910_assignment1/wandb/run-20240228_154707-09md131f/logs/debug.log
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sadbhawna/Desktop/cs6910_assignment1/wandb/run-20240228_154707-09md131f/logs/debug-internal.log
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():566] calling init triggers
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():573] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'dataset': 'fashion_mnist', 'epochs': 25, 'eps': 0.0001, 'hidden_size': 128, 'learning_rate': 0.01, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'adam', 'wandb_project': 'cs23d014_assignment_1', 'weight_decay': 0.0005, 'weight_ini': 'He Normal'}
config: {}
2024-02-28 15:47:07,540 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():616] starting backend
2024-02-28 15:47:07,541 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():620] setting up manager
2024-02-28 15:47:07,550 INFO    Thread-11 (_run_job):8170 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-28 15:47:07,550 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():628] backend started and connected
2024-02-28 15:47:07,560 INFO    Thread-11 (_run_job):8170 [wandb_run.py:_config_callback():1343] config_cb None None {'activation': 'relu', 'batch_size': 16, 'dataset': 'fashion_mnist', 'epochs': 25, 'eps': 0.0001, 'hidden_size': 128, 'learning_rate': 0.01, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'adam', 'wandb_project': 'cs23d014_assignment_1', 'weight_decay': 0.0005, 'weight_ini': 'He Normal'}
2024-02-28 15:47:07,560 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():720] updated telemetry
2024-02-28 15:47:07,564 INFO    Thread-11 (_run_job):8170 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-28 15:47:08,195 INFO    Thread-11 (_run_job):8170 [wandb_run.py:_on_init():2262] communicating current version
2024-02-28 15:47:12,198 WARNING MsgRouterThr:8170 [router.py:message_loop():77] message_loop has been closed
2024-02-28 15:47:13,457 ERROR   Thread-11 (_run_job):8170 [wandb_init.py:init():1194] transport failed
Traceback (most recent call last):
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 802, in init
    run._on_init()
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2266, in _on_init
    version_result = version_handle.wait(timeout=30)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
