
----------->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> mean_squared_error <function sigmoid at 0x7fa027923ce0>
[34m[1mwandb[39m[22m: [33mWARNING[39m Ignored wandb.init() arg project when running a sweep.
/home/sadbhawna/Desktop/cs6910_assignment1/activation.py:16: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
/home/sadbhawna/Desktop/cs6910_assignment1/optimizers.py:40: RuntimeWarning: overflow encountered in square
  l2_reg_loss += np.sum(np.square(nn.parameters['W' + str(l)]))
/home/sadbhawna/Desktop/cs6910_assignment1/optimizers.py:41: RuntimeWarning: invalid value encountered in scalar multiply
  l2_reg_loss = (weight_decay / (2 * m)) * l2_reg_loss
/home/sadbhawna/Desktop/cs6910_assignment1/activation.py:19: RuntimeWarning: overflow encountered in multiply
  return x * (1 - x)
/home/sadbhawna/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
